# Generated by Django 6.0.3 on 2026-04-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdetails',
            old_name='subject',
            new_name='class_detail',
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='enquired_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
