# Generated by Django 6.0.3 on 2026-04-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_rename_subject_applicationdetails_class_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdetails',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('Common', 'Common')], default='Common', max_length=10),
        ),
    ]
